version: "3" # ファイルフォーマットのバージョン
services:
  db: #サービスの名称：データベース
    image: mysql:8.0.22 # DockerリポジトリからPullするDockerイメージを指定
    container_name: ${PROJECT_NAME}_db # コンテナの名称
    restart: always # コンテナの再起動を実施
    environment:
      MYSQL_ROOT_PASSWORD: pass # mysqlのルートパスワード
      MYSQL_DATABASE: ${PROJECT_NAME}_db #mysql内のデータベース名
      MYSQL_USER: user # mysqlへログインする際のユーザー名
      MYSQL_PASSWORD: pass # mysqlへログインする際のパスワード
    volumes:
      - db_data:/var/lib/mysql
  wordpress: # サービスの名称：wordpress
    image: wordpress:latest
    container_name: ${PROJECT_NAME}_wp
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: ${PROJECT_NAME}_db
      WORDPRESS_DEBUG: 1
    volumes: # 作業フォルダの同期（コンテナ側ディレクトリをホスト側へマウント）
      - ./src/wp-content/themes/${PROJECT_NAME}:/var/www/html/wp-content/themes/${PROJECT_NAME}
      - ./src/wp-content/plugins:/var/www/html/wp-content/plugins
    env_file: .env
volumes:
  wordpress:
  db_data:
