version: "3"
services:
  db:
    image: mysql:8.0.22
    container_name: ${PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ${PROJECT_NAME}_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    container_name: ${PROJECT_NAME}_wp
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: ${PROJECT_NAME}_db
      WORDPRESS_DEBUG: 1
    volumes:
      - ./src/wp-content/themes/${PROJECT_NAME}:/var/www/html/wp-content/themes/${PROJECT_NAME}
      - ./src/wp-content/plugins:/var/www/html/wp-content/plugins
    env_file: .env
volumes:
  wordpress:
  db_data:
